---
- name: Asegurar que UFW esté instalado
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Activar UFW (firewall)
  ufw:
    state: enabled
    policy: deny

- name: Asegurar configuración de SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  loop:
    - { regexp: '^#?Port\\s+.*', line: 'Port 2222' }
    - { regexp: '^#?PermitRootLogin\\s+.*', line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication\\s+.*', line: 'PasswordAuthentication no' }

- name: Reiniciar servicio SSH para aplicar cambios
  service:
    name: ssh
    state: restarted
