---
- name: Actualizar paquetes del sistema
  apt:
    update_cache: yes
    upgrade: dist

- name: Eliminar servicios innecesarios
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - telnet
    - ftp
    - rsh-client
    - rsh-server
    - xinetd
    - talk
    - tftp
